# Supply Chain Performance & Risk Analytics
## Phase 1 — Exploratory Data Analysis & Cleaning
**Dataset:** USAID SCMS Delivery History Dataset  
**Rows:** 10,324 | **Columns:** 33  
**Author:** Manohar Choudhary

In [1]:
# import libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
print(os.getcwd())

C:\Users\lenovo\OneDrive\Desktop\supply-chain-performance-analytics\python_code

In [2]:
df = pd.read_csv(
    "../data/raw_data/SCMS_Delivery_History_Dataset_20150929.csv",
    encoding="latin1"
)
print(df.shape)

(10324, 33)

In [4]:
df.shape

(10324, 33)

In [5]:
print("Shape:", df.shape)
print("Columns:", df.columns.tolist())

Shape: (10324, 33)
Columns: ['ID', 'Project Code', 'PQ #', 'PO / SO #', 'ASN/DN #', 'Country', 'Managed By', 'Fulfill Via', 'Vendor INCO Term', 'Shipment Mode', 'PQ First Sent to Client Date', 'PO Sent to Vendor Date', 'Scheduled Delivery Date', 'Delivered to Client Date', 'Delivery Recorded Date', 'Product Group', 'Sub Classification', 'Vendor', 'Item Description', 'Molecule/Test Type', 'Brand', 'Dosage', 'Dosage Form', 'Unit of Measure (Per Pack)', 'Line Item Quantity', 'Line Item Value', 'Pack Price', 'Unit Price', 'Manufacturing Site', 'First Line Designation', 'Weight (Kilograms)', 'Freight Cost (USD)', 'Line Item Insurance (USD)']

## Initial Exploration
Checking data types, null counts, and basic statistics before cleaning.

In [6]:
# datatype and null inspection

print(df.dtypes)
print("\nNull counts:")
print(df.isnull().sum())
print("\nNull percentages:")
print((df.isnull().sum() / len(df)) * 100)

ID                                int64
Project Code                     object
PQ #                             object
PO / SO #                        object
ASN/DN #                         object
Country                          object
Managed By                       object
Fulfill Via                      object
Vendor INCO Term                 object
Shipment Mode                    object
PQ First Sent to Client Date     object
PO Sent to Vendor Date           object
Scheduled Delivery Date          object
Delivered to Client Date         object
Delivery Recorded Date           object
Product Group                    object
Sub Classification               object
Vendor                           object
Item Description                 object
Molecule/Test Type               object
Brand                            object
Dosage                           object
Dosage Form                      object
Unit of Measure (Per Pack)        int64
Line Item Quantity                int64
Line Item Value                 float64
Pack Price                      float64
Unit Price                      float64
Manufacturing Site               object
First Line Designation           object
Weight (Kilograms)               object
Freight Cost (USD)               object
Line Item Insurance (USD)       float64
dtype: object

Null counts:
ID                                 0
Project Code                       0
PQ #                               0
PO / SO #                          0
ASN/DN #                           0
Country                            0
Managed By                         0
Fulfill Via                        0
Vendor INCO Term                   0
Shipment Mode                    360
PQ First Sent to Client Date       0
PO Sent to Vendor Date             0
Scheduled Delivery Date            0
Delivered to Client Date           0
Delivery Recorded Date             0
Product Group                      0
Sub Classification                 0
Vendor                             0
Item Description                   0
Molecule/Test Type                 0
Brand                              0
Dosage                          1736
Dosage Form                        0
Unit of Measure (Per Pack)         0
Line Item Quantity                 0
Line Item Value                    0
Pack Price                         0
Unit Price                         0
Manufacturing Site                 0
First Line Designation             0
Weight (Kilograms)                 0
Freight Cost (USD)                 0
Line Item Insurance (USD)        287
dtype: int64

Null percentages:
ID                               0.000000
Project Code                     0.000000
PQ #                             0.000000
PO / SO #                        0.000000
ASN/DN #                         0.000000
Country                          0.000000
Managed By                       0.000000
Fulfill Via                      0.000000
Vendor INCO Term                 0.000000
Shipment Mode                    3.487021
PQ First Sent to Client Date     0.000000
PO Sent to Vendor Date           0.000000
Scheduled Delivery Date          0.000000
Delivered to Client Date         0.000000
Delivery Recorded Date           0.000000
Product Group                    0.000000
Sub Classification               0.000000
Vendor                           0.000000
Item Description                 0.000000
Molecule/Test Type               0.000000
Brand                            0.000000
Dosage                          16.815188
Dosage Form                      0.000000
Unit of Measure (Per Pack)       0.000000
Line Item Quantity               0.000000
Line Item Value                  0.000000
Pack Price                       0.000000
Unit Price                       0.000000
Manufacturing Site               0.000000
First Line Designation           0.000000
Weight (Kilograms)               0.000000
Freight Cost (USD)               0.000000
Line Item Insurance (USD)        2.779930
dtype: float64

In [7]:
#Column investigation (Freight Cost, Weight, Shipment Mode)

print("Freight Cost sample values:")
print(df["Freight Cost (USD)"].tail(10))

print("\nWeight sample values:")
print(df["Weight (Kilograms)"].tail(10))

print("\nShipment Mode unique values:")
print(df["Shipment Mode"].value_counts(dropna=False))

Freight Cost sample values:
10314               See DN-4274 (ID#:84472)
10315                                 26180
10316                                  3410
10317               See DN-4282 (ID#:83919)
10318               See DN-4307 (ID#:83920)
10319               See DN-4307 (ID#:83920)
10320               See DN-4313 (ID#:83921)
10321    Freight Included in Commodity Cost
10322    Freight Included in Commodity Cost
10323    Freight Included in Commodity Cost
Name: Freight Cost (USD), dtype: object

Weight sample values:
10314       See DN-4274 (ID#:84472)
10315                         15198
10316                          1547
10317       See DN-4282 (ID#:83919)
10318       See DN-4307 (ID#:83920)
10319       See DN-4307 (ID#:83920)
10320       See DN-4313 (ID#:83921)
10321    Weight Captured Separately
10322                          1392
10323    Weight Captured Separately
Name: Weight (Kilograms), dtype: object

Shipment Mode unique values:
Shipment Mode
Air            6113
Truck          2830
Air Charter     650
Ocean           371
NaN             360
Name: count, dtype: int64

## Data Cleaning
All cleaning steps applied in sequence. Each step documented in issue_log.md

In [8]:
# Issue 006 - Freight Type flag
df["Freight_Type"] = np.where(
    df["Freight Cost (USD)"].str.contains(r"[A-Za-z]", na=False),
    "Absorbed", "Separate"
)

# Issue 006 - Convert Freight Cost to numeric
df["Freight Cost (USD)"] = pd.to_numeric(
    df["Freight Cost (USD)"], errors="coerce"
)

# Issue 007 - Weight Type flag
df["Weight_Type"] = np.where(
    df["Weight (Kilograms)"].str.contains(r"[A-Za-z]", na=False),
    "Captured Separately", "Recorded"
)

# Issue 007 - Convert Weight to numeric
df["Weight (Kilograms)"] = pd.to_numeric(
    df["Weight (Kilograms)"], errors="coerce"
)

# Issue 005 - Convert date columns
# ── Issue 005 ── Convert three clean date columns
date_columns = [
    "Scheduled Delivery Date",
    "Delivered to Client Date",
    "Delivery Recorded Date"
]
for col in date_columns:
    df[col] = pd.to_datetime(df[col], errors="coerce", format="%d-%b-%y")

# ── Issue 009 ── Convert two mixed date columns
mixed_date_columns = [
    "PQ First Sent to Client Date",
    "PO Sent to Vendor Date"
]
for col in mixed_date_columns:
    df[col] = pd.to_datetime(df[col], errors="coerce", format="%m/%d/%Y")

# Issue 004 - Fill insurance nulls
df["Line Item Insurance (USD)"] = df["Line Item Insurance (USD)"].fillna(0)

print("Cleaning complete.")
print("Shape after cleaning:", df.shape)

Cleaning complete.
Shape after cleaning: (10324, 35)

In [9]:
# varification after cleaning

print("Remaining nulls:")
print(df.isnull().sum()[df.isnull().sum() > 0])

print("\nData types after cleaning:")
print(df.dtypes)

print("\nFreight_Type distribution:")
print(df["Freight_Type"].value_counts())

print("\nWeight_Type distribution:")
print(df["Weight_Type"].value_counts())

Remaining nulls:
Shipment Mode                    360
PQ First Sent to Client Date    2681
PO Sent to Vendor Date          5732
Dosage                          1736
Weight (Kilograms)              3952
Freight Cost (USD)              4126
dtype: int64

Data types after cleaning:
ID                                       int64
Project Code                            object
PQ #                                    object
PO / SO #                               object
ASN/DN #                                object
Country                                 object
Managed By                              object
Fulfill Via                             object
Vendor INCO Term                        object
Shipment Mode                           object
PQ First Sent to Client Date    datetime64[ns]
PO Sent to Vendor Date          datetime64[ns]
Scheduled Delivery Date         datetime64[ns]
Delivered to Client Date        datetime64[ns]
Delivery Recorded Date          datetime64[ns]
Product Group                           object
Sub Classification                      object
Vendor                                  object
Item Description                        object
Molecule/Test Type                      object
Brand                                   object
Dosage                                  object
Dosage Form                             object
Unit of Measure (Per Pack)               int64
Line Item Quantity                       int64
Line Item Value                        float64
Pack Price                             float64
Unit Price                             float64
Manufacturing Site                      object
First Line Designation                  object
Weight (Kilograms)                     float64
Freight Cost (USD)                     float64
Line Item Insurance (USD)              float64
Freight_Type                            object
Weight_Type                             object
dtype: object

Freight_Type distribution:
Freight_Type
Separate    6198
Absorbed    4126
Name: count, dtype: int64

Weight_Type distribution:
Weight_Type
Recorded               6372
Captured Separately    3952
Name: count, dtype: int64

In [22]:
# Flag whether Dosage is applicable for the product group
df["Dosage_Applicable"] = np.where(
    df["Product Group"].isin(["HRDT", "MRDT"]),
    "Not Applicable", "Applicable"
)

# Verify
print(df["Dosage_Applicable"].value_counts())
print(df[["Product Group", "Dosage", "Dosage_Applicable"]].head(20))

Dosage_Applicable
Applicable        8588
Not Applicable    1736
Name: count, dtype: int64
   Product Group     Dosage Dosage_Applicable
0           HRDT        NaN    Not Applicable
1            ARV    10mg/ml        Applicable
2           HRDT        NaN    Not Applicable
3            ARV      150mg        Applicable
4            ARV       30mg        Applicable
5            ARV    10mg/ml        Applicable
6            ARV      200mg        Applicable
7            ARV      200mg        Applicable
8            ARV       30mg        Applicable
9            ARV   200/50mg        Applicable
10           ARV   200/50mg        Applicable
11          HRDT        NaN    Not Applicable
12          HRDT        NaN    Not Applicable
13           ARV  150/300mg        Applicable
14          HRDT        NaN    Not Applicable
15           ARV      200mg        Applicable
16          HRDT        NaN    Not Applicable
17          HRDT        NaN    Not Applicable
18           ARV         2g        Applicable
19          HRDT        NaN    Not Applicable

In [23]:
df.shape

(10324, 39)

# Feature engineering -

**Creating new column for analysis assistance**

In [19]:
# ── Feature Engineering ──
df["Delivery_Delay_Days"] = (
    df["Delivered to Client Date"] - df["Scheduled Delivery Date"]
).dt.days

df["On_Time_Delivery"] = np.where(
    df["Delivery_Delay_Days"] <= 2, "On Time", "Late"
)

df["Delivery_Status"] = np.where(
    df["Delivery_Delay_Days"] < 0, "Early",
    np.where(df["Delivery_Delay_Days"] <= 2, "On Time", "Late")
)

# ── Export cleaned data ──
df.to_csv(
    "../data/processed_data/scms_cleaned.csv",
    index=False,
    encoding="utf-8"
)
print("Exported. Final shape:", df.shape)
print("Columns:", df.columns.tolist())

Exported. Final shape: (10324, 38)
Columns: ['ID', 'Project Code', 'PQ #', 'PO / SO #', 'ASN/DN #', 'Country', 'Managed By', 'Fulfill Via', 'Vendor INCO Term', 'Shipment Mode', 'PQ First Sent to Client Date', 'PO Sent to Vendor Date', 'Scheduled Delivery Date', 'Delivered to Client Date', 'Delivery Recorded Date', 'Product Group', 'Sub Classification', 'Vendor', 'Item Description', 'Molecule/Test Type', 'Brand', 'Dosage', 'Dosage Form', 'Unit of Measure (Per Pack)', 'Line Item Quantity', 'Line Item Value', 'Pack Price', 'Unit Price', 'Manufacturing Site', 'First Line Designation', 'Weight (Kilograms)', 'Freight Cost (USD)', 'Line Item Insurance (USD)', 'Freight_Type', 'Weight_Type', 'Delivery_Delay_Days', 'On_Time_Delivery', 'Delivery_Status']

In [7]:
df[["Delivery_Delay_Days","On_Time_Delivery"]]

       Delivery_Delay_Days On_Time_Delivery
0                        0          On Time
1                        0          On Time
2                        0          On Time
3                        0          On Time
4                        0          On Time
...                    ...              ...
10319                  -16          On Time
10320                    6             Late
10321                   -6          On Time
10322                  -36          On Time
10323                  -27          On Time

[10324 rows x 2 columns]

In [18]:
df[["Delivery_Delay_Days","On_Time_Delivery","Delivery_Delay_Days"]]

       Delivery_Delay_Days On_Time_Delivery  Delivery_Delay_Days
0                        0          On Time                    0
1                        0          On Time                    0
2                        0          On Time                    0
3                        0          On Time                    0
4                        0          On Time                    0
...                    ...              ...                  ...
10319                  -16          On Time                  -16
10320                    6             Late                    6
10321                   -6          On Time                   -6
10322                  -36          On Time                  -36
10323                  -27          On Time                  -27

[10324 rows x 3 columns]

In [15]:
df.head(10)

,ID,Project Code,PQ #,PO / SO #,ASN/DN #,Country,Managed By,Fulfill Via,Vendor INCO Term,Shipment Mode,...,Manufacturing Site,First Line Designation,Weight (Kilograms),Freight Cost (USD),Line Item Insurance (USD),Freight_Type,Weight_Type,Delivery_Delay_Days,On_Time_Delivery,Delivery_Status
0,1,100-CI-T01,Pre-PQ Process,SCMS-4,ASN-8,Côte d'Ivoire,PMO - US,Direct Drop,EXW,Air,...,Ranbaxy Fine Chemicals LTD,Yes,13.0,780.34,0.0,Separate,Recorded,0,On Time,On Time
1,3,108-VN-T01,Pre-PQ Process,SCMS-13,ASN-85,Vietnam,PMO - US,Direct Drop,EXW,Air,...,"Aurobindo Unit III, India",Yes,358.0,4521.50,0.0,Separate,Recorded,0,On Time,On Time
2,4,100-CI-T01,Pre-PQ Process,SCMS-20,ASN-14,Côte d'Ivoire,PMO - US,Direct Drop,FCA,Air,...,ABBVIE GmbH & Co.KG Wiesbaden,Yes,171.0,1653.78,0.0,Separate,Recorded,0,On Time,On Time
3,15,108-VN-T01,Pre-PQ Process,SCMS-78,ASN-50,Vietnam,PMO - US,Direct Drop,EXW,Air,...,"Ranbaxy, Paonta Shahib, India",Yes,1855.0,16007.06,0.0,Separate,Recorded,0,On Time,On Time
4,16,108-VN-T01,Pre-PQ Process,SCMS-81,ASN-55,Vietnam,PMO - US,Direct Drop,EXW,Air,...,"Aurobindo Unit III, India",Yes,7590.0,45450.08,0.0,Separate,Recorded,0,On Time,On Time
5,23,112-NG-T01,Pre-PQ Process,SCMS-87,ASN-57,Nigeria,PMO - US,Direct Drop,EXW,Air,...,"Aurobindo Unit III, India",Yes,504.0,5920.42,0.0,Separate,Recorded,0,On Time,On Time
6,44,110-ZM-T01,Pre-PQ Process,SCMS-139,ASN-130,Zambia,PMO - US,Direct Drop,DDU,Air,...,MSD South Granville Australia,Yes,328.0,NaN,0.0,Absorbed,Recorded,0,On Time,On Time
7,45,109-TZ-T01,Pre-PQ Process,SCMS-140,ASN-94,Tanzania,PMO - US,Direct Drop,EXW,Air,...,"Aurobindo Unit III, India",Yes,1478.0,6212.41,0.0,Separate,Recorded,0,On Time,On Time
8,46,112-NG-T01,Pre-PQ Process,SCMS-156,ASN-93,Nigeria,PMO - US,Direct Drop,EXW,Air,...,"Aurobindo Unit III, India",No,NaN,NaN,0.0,Absorbed,Captured Separately,0,On Time,On Time
9,47,110-ZM-T01,Pre-PQ Process,SCMS-165,ASN-199,Zambia,PMO - US,Direct Drop,CIP,Air,...,ABBVIE (Abbott) St. P'burg USA,Yes,643.0,NaN,0.0,Absorbed,Recorded,0,On Time,On Time

In [24]:
print(df["Delivery_Status"].value_counts())
print(df["Delivery_Status"].str.len().max())

Delivery_Status
On Time    6464
Early      2814
Late       1046
Name: count, dtype: int64
7

In [14]:
print(df.columns.tolist())

['ID', 'Project Code', 'PQ #', 'PO / SO #', 'ASN/DN #', 'Country', 'Managed By', 'Fulfill Via', 'Vendor INCO Term', 'Shipment Mode', 'PQ First Sent to Client Date', 'PO Sent to Vendor Date', 'Scheduled Delivery Date', 'Delivered to Client Date', 'Delivery Recorded Date', 'Product Group', 'Sub Classification', 'Vendor', 'Item Description', 'Molecule/Test Type', 'Brand', 'Dosage', 'Dosage Form', 'Unit of Measure (Per Pack)', 'Line Item Quantity', 'Line Item Value', 'Pack Price', 'Unit Price', 'Manufacturing Site', 'First Line Designation', 'Weight (Kilograms)', 'Freight Cost (USD)', 'Line Item Insurance (USD)', 'Freight_Type', 'Weight_Type', 'Delivery_Delay_Days', 'On_Time_Delivery', 'Delivery_Status']

In [26]:
df.shape

(10324, 39)

In [21]:
# Print column index positions
for i, col in enumerate(df.columns):
    print(i, col)

0 ID
1 Project Code
2 PQ #
3 PO / SO #
4 ASN/DN #
5 Country
6 Managed By
7 Fulfill Via
8 Vendor INCO Term
9 Shipment Mode
10 PQ First Sent to Client Date
11 PO Sent to Vendor Date
12 Scheduled Delivery Date
13 Delivered to Client Date
14 Delivery Recorded Date
15 Product Group
16 Sub Classification
17 Vendor
18 Item Description
19 Molecule/Test Type
20 Brand
21 Dosage
22 Dosage Form
23 Unit of Measure (Per Pack)
24 Line Item Quantity
25 Line Item Value
26 Pack Price
27 Unit Price
28 Manufacturing Site
29 First Line Designation
30 Weight (Kilograms)
31 Freight Cost (USD)
32 Line Item Insurance (USD)
33 Freight_Type
34 Weight_Type
35 Delivery_Delay_Days
36 On_Time_Delivery
37 Delivery_Status